# Generated by Django 3.2.15 on 2022-10-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGeo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('lon', models.DecimalField(decimal_places=14, max_digits=16)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=16)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
