# Generated by Django 3.2.15 on 2022-12-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceGeolocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Адрес')),
                ('lon', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Долгота')),
                ('lat', models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Широта')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
        ),
    ]
