# Generated by Django 3.2.15 on 2022-10-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0002_rename_ordergeo_placegeo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placegeo',
            name='last_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='placegeo',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='placegeo',
            name='lon',
            field=models.DecimalField(decimal_places=14, max_digits=16, verbose_name='Долгота'),
        ),
    ]
