# Generated by Django 3.2.15 on 2022-10-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0003_auto_20221014_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaceGeo',
            new_name='PlaceGeolocation',
        ),
    ]
