# Generated by Django 3.2.15 on 2022-09-14 18:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('order_items', models.ManyToManyField(to='foodcartapp.Product')),
            ],
            options={
                'verbose_name': ('Заказ',),
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='orders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='foodcartapp.order'),
        ),
    ]
