# Generated by Django 3.2.15 on 2022-09-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_products_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_surname',
            new_name='lastname',
        ),
    ]
