# Generated by Django 3.2.15 on 2022-09-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20220919_2044'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
            ],
        ),
    ]
