# Generated by Django 3.2.15 on 2022-09-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='item_price',
        ),
    ]
