# Generated by Django 3.2.15 on 2022-09-22 16:15

from django.db import migrations
from django.db.models import F, Subquery, OuterRef


def assign_item_price(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    Product = apps.get_model('foodcartapp', 'Product')
    OrderItem.objects.annotate(
        product_price=Subquery(Product.objects.filter(id=OuterRef('product')).values('price'))
    ).all().update(
        item_price=F('product_price') * F('quantity')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_rename_price_orderitem_item_price'),
    ]

    operations = [
        migrations.RunPython(assign_item_price)
    ]
