# Generated by Django 3.2.15 on 2022-09-27 16:25

from django.db import migrations


def add_order_status(apps, schema):
    NOT_PROCESSED = 'NP'
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.update(status=NOT_PROCESSED)


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220927_1924'),
    ]

    operations = [
        migrations.RunPython(add_order_status)
    ]
