# Generated by Django 3.2.15 on 2022-09-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20220927_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NP', 'Необработанный'), ('PR', 'Обработанный'), ('FN', 'Завершенный')], db_index=True, default='NP', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
