# Generated by Django 3.2.15 on 2022-09-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220927_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
    ]
