# Generated by Django 3.2.15 on 2022-09-28 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20220928_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Зарегистрирован'),
        ),
    ]
