# Generated by Django 3.2.15 on 2022-09-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('El', 'Банковской картой'), ('Ca', 'Наличными')], default='Ca', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
