# Generated by Django 3.2.15 on 2022-10-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_order_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='foodcartapp.restaurant'),
        ),
    ]
