# Generated by Django 3.2.15 on 2022-10-10 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_auto_20221010_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status', 'registered_at'], 'verbose_name': ('Заказ',), 'verbose_name_plural': 'Заказы'},
        ),
    ]
