# Generated by Django 3.2.15 on 2022-10-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0065_alter_orderitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('El', 'Банковской картой'), ('Ca', 'Наличными')], max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
